name: Speed Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged || github.event.schedule == '0 0 * * *' }}
    runs-on: ubuntu-latest
    env:
      MYSQL_ARG: "--mysql-host=${{ secrets.MYSQL_HOST }} --mysql-user=${{ secrets.MYSQL_USER }} --mysql-password=${{ secrets.MYSQL_PASSWORD }} --mysql-db=${{ secrets.MYSQL_DB }}"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: fetch all branch
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 60
          shell: bash
          command: git fetch --depth=1
      - name: config
        run: ./config --strict-warnings enable-zuc enable-ntls enable-sm2 enable-sm3 enable-sm4 enable-fips --api=1.1.1 && perl configdata.pm --dump
      - name: make
        run: make -j4
      - name: Set current date as env variable
        run: |
          NOW=$(date +'%F~%T')
          echo "NOW=$NOW" >> $GITHUB_ENV
          echo "JOB_DATE='$NOW'" | sed 's/~/ /g' >> $GITHUB_ENV
      - name: save cpu and memory info
        shell: bash
        run: |
          mkdir -p speed/cpu
          mkdir -p speed/mem
          lscpu > speed/cpu/$NOW.txt

          CPUS_FILE="/sys/fs/cgroup/cpuset/cpuset.cpus"
          CPUQ_FILE="/sys/fs/cgroup/cpu/cpu.cfs_quota_us"
          CPUP_FILE="/sys/fs/cgroup/cpu/cpu.cfs_period_us"
          MEM_FILE="/sys/fs/cgroup/memory/memory.limit_in_bytes"

          if [ -f "$CPUS_FILE" ]; then
            CPUS=$(cat $CPUS_FILE)
            echo "$CPUS_FILE: $CPUS" >> speed/cpu/$NOW.txt
          else
            echo "$CPUS_FILE: (not found)" >> speed/cpu/$NOW.txt
          fi

          if [ -f "$CPUQ_FILE" ]; then
            CPUQ=$(cat $CPUQ_FILE)
            echo "$CPUQ_FILE: $CPUQ" >> speed/cpu/$NOW.txt
          else
            echo "$CPUQ_FILE: (not found)" >> speed/cpu/$NOW.txt
          fi

          if [ -f "$CPUP_FILE" ]; then
            CPUP=$(cat $CPUP_FILE)
            echo "$CPUP_FILE: $CPUP" >> speed/cpu/$NOW.txt
          else
            echo "$CPUP_FILE: (not found)" >> speed/cpu/$NOW.txt
          fi

          free -mh > speed/mem/$NOW.txt

          if [ -f "$MEM_FILE" ]; then
            MEM=$(cat $MEM_FILE)
            echo "$MEM_FILE: $MEM" >> speed/mem/$NOW.txt
          else
            echo "$MEM_FILE: (not found)" >> speed/mem/$NOW.txt
          fi
      # ... Rest of your workflow steps unchanged ...
